ci: update pre-run job

diff --git a/.github/actions/kurtosis-pre-run/action.yml b/.github/actions/kurtosis-pre-run/action.yml
--- a/.github/actions/kurtosis-pre-run/action.yml
+++ b/.github/actions/kurtosis-pre-run/action.yml
@@ -16,6 +16,7 @@ inputs:
 runs:
   using: composite
   steps:
+    # Install dependencies
     - name: Install kurtosis
       shell: bash
       run: |
@@ -43,6 +44,7 @@ runs:
       with:
         version: v1.0.0
 
+    # Login to Docker registry if credentials are provided
     - name: Login to docker registry
       if: ${{ inputs.docker_username && inputs.docker_token }}
       uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
@@ -50,33 +52,7 @@ runs:
         username: ${{ inputs.docker_username }}
         password: ${{ inputs.docker_token }}
 
-    - uses: google-github-actions/auth@v2.0.0
-      with:
-        workload_identity_provider: 'projects/337907489413/locations/global/workloadIdentityPools/github-wif/providers/github'
-        service_account: 'kurtosis-cdk-ci@prj-polygonlabs-devtools-dev.iam.gserviceaccount.com'
-
-    - name: Pull kurtosis core components from GCR
-      if: ${{ inputs.pull_images_from_gcr == 'true' }}
-      shell: bash
-      run: |
-        registry="europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/virtual"
-        gcloud auth configure-docker europe-west2-docker.pkg.dev
-
-        docker pull "${registry}/timberio/vector:0.45.0-debian"
-        docker tag "${registry}/timberio/vector:0.45.0-debian" timberio/vector:0.45.0-debian
-
-        docker pull "${registry}/badouralix/curl-jq:latest"
-        docker tag "${registry}/badouralix/curl-jq:latest" badouralix/curl-jq:latest
-
-        docker pull "${registry}/traefik:2.10.6"
-        docker tag "${registry}/traefik:2.10.6" traefik:2.10.6
-
-        docker pull "${registry}/alpine:3.17"
-        docker tag "${registry}/alpine:3.17" alpine:3.17
-
-        docker pull "${registry}/kurtosistech/engine:1.7.2"
-        docker tag "${registry}/kurtosistech/engine:1.7.2" kurtosistech/engine:1.7.2
-
+    # Pull images from GCR if specified
     - uses: actions/setup-python@v4
       if: ${{ inputs.pull_images_from_gcr == 'true' }}
       with:
@@ -85,4 +61,51 @@ runs:
     - name: Add registry prefix to image names
       if: ${{ inputs.pull_images_from_gcr == 'true' }}
       shell: bash
-      run: python3 scripts/add-registry-prefix.py --registry-prefix "europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/virtual"
+      run: python3 .github/scripts/add-registry-prefix.py --registry-prefix "europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/virtual"
+
+    - uses: google-github-actions/auth@v2.0.0
+      if: ${{ inputs.pull_images_from_gcr == 'true' }}
+      with:
+        workload_identity_provider: "projects/337907489413/locations/global/workloadIdentityPools/github-wif/providers/github"
+        service_account: "kurtosis-cdk-ci@prj-polygonlabs-devtools-dev.iam.gserviceaccount.com"
+
+    - name: Configure Docker to use GCR
+      if: ${{ inputs.pull_images_from_gcr == 'true' }}
+      run: gcloud auth configure-docker europe-west2-docker.pkg.dev
+
+    - name: Pre pull package images from GCR
+      if: ${{ inputs.pull_images_from_gcr == 'true' }}
+      shell: bash
+      run: |
+        file="modified-images.txt"
+        total_images=$(wc -l < "$file")
+        current=0
+        while IFS= read -r image; do
+          # Skip empty lines
+          [[ -z "$image" ]] && continue
+
+          current=$((current + 1))
+          echo "[$current/$total_images] Pulling: $image"
+          if ! docker pull "$image"; then
+            echo "Failed to pull image: $image"
+            exit 1
+          fi
+        done < "$file"
+
+    - name: Pre pull kurtosis core images from GCR
+      if: ${{ inputs.pull_images_from_gcr == 'true' }}
+      shell: bash
+      run: |
+        registry="europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/virtual"
+        images=(
+          "timberio/vector:0.45.0-debian"
+          "badouralix/curl-jq:latest"
+          "traefik:2.10.6"
+          "alpine:3.17"
+          "kurtosistech/engine:1.7.2"
+        )
+        for image in "${images[@]}"; do
+          echo "Pulling: $image"
+          docker pull "${registry}/${image}"
+          docker tag "${registry}/${image}" "${image}"
+        done
