ci: fix typo in validate test combinaton job

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,29 +53,7 @@ jobs:
           name: dump_run_without_args_${{ github.run_id }}
           path: ./dump
 
-  validate-test-combinations:
-    name: Check test combinations
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      
-      - name: Generate test combinations
-        working-directory: .github/tests
-        run: ./combine-ymls.sh
-
-      - name: Check if test combinations are up to date
-        run: |
-          if [[ -n $(git status --porcelain) ]]; then
-            echo "❌ Error: Test combinations files are not up to date. Please run \`make gen\`."
-            git status --porcelain
-            git diff
-            exit 1
-          else
-            echo "✅ Test combinations are up to date."
-          fi
-
   list-ymls:
-    needs: validate-test-combinations
     runs-on: ubuntu-latest
     timeout-minutes: 5
     outputs:
@@ -86,6 +64,17 @@ jobs:
       - name: Generate test combinations
         working-directory: .github/tests
         run: ./combine-ymls.sh
+      
+      - name: Check if test combinations are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Test combinations files are not up to date. Please run \`./combine-ymls.sh\` in the \`.github/tests/\` directory."
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Test combinations are up to date."
+          fi
 
       - id: set-matrix
         # List all yml files in the .github/tests directory, as well as test combinations, except for the additional-services.yml file.
