fix: replace verified batch number check for pp network
Signed-off-by: Ji Hwan <jkim@polygon.technology>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -361,11 +361,23 @@ jobs:
             --rpc-url "$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-002 rpc)"
 
       - name: Monitor verified batches of the third PP L2 chain (CDK Erigon Permissionless RPC)
-        working-directory: .github/scripts
         run: |
-          ./monitor-verified-batches.sh \
-            --enclave ${{ env.ENCLAVE_NAME }} \
-            --rpc-url "$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)"
+          echo "Sending a transaction to the PP network Erigon RPC..."
+          cast send \
+            --legacy \
+            --timeout 30 \
+            --rpc-url "$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)" \
+            --private-key "0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625" \
+            --gas-limit 100000 \
+            --create 0x6001617000526160006110005ff05b6109c45a111560245761600061100080833c600e565b50
+          ret_code=$?
+          if [[ $ret_code -eq 0 ]]; then
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Transaction successfuly sent!"
+              exit 0
+          else
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Transaction failed!"
+              exit 1
+          fi
 
       - name: Dump enclave
         if: ${{ !cancelled() }}
