test: add additional step in CI to bridge from third PP network to first rollup.
Signed-off-by: Ji Hwan <jkim@polygon.technology>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -404,6 +404,46 @@ jobs:
               exit 1
           fi
 
+      - name: Bridge from third PP L2 chain to first Rollup chain.
+        working-directory: .github/scripts
+        run: |
+          echo "Sending a bridge transaction from L1 to the PP network Erigon RPC..."
+          originNetworkURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)
+          # Deposit Usage: <program_name> <originBridgeAddr> <originAccHexAddress> <originAccHexPrivateKey> <originNetworkURL> <fundsToSend> <destNetwork>
+          ./deposit \
+          "0xd8886e9D827218a02B8C04323b5550f2F36BC8d5" \
+          "0xE34aaF64b29273B7D567FCFc40544c014EEe9970" \
+          "0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625" \
+          "http://$originNetworkURL" \
+          "1231231" \
+          "3"
+          if [[ $ret_code -eq 0 ]]; then
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit Transaction successfuly sent!"
+          else
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit Transaction failed!"
+              exit 1
+          fi
+
+          echo "Waiting for deposit to be claimable..."
+          sleep 60
+
+          destNetworkURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc)
+          bridgeURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-bridge-service-001 rpc)
+          # Claim Usage: <program_name> <destBridgeAddr> <destAccHexAddress> <destAccHexPrivateKey> <destNetworkURL> <bridgeURL>
+          ./claim \
+          "0xd8886e9D827218a02B8C04323b5550f2F36BC8d5" \
+          "0xE34aaF64b29273B7D567FCFc40544c014EEe9970" \
+          "0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625" \
+          "$destNetworkURL" \
+          "$bridgeURL"
+          if [[ $ret_code -eq 0 ]]; then
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim Transaction successfuly sent!"
+              exit 0
+          else
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim Transaction failed!"
+              exit 1
+          fi
+          
       - name: Dump enclave
         if: ${{ !cancelled() }}
         run: kurtosis enclave dump ${{ env.ENCLAVE_NAME }} ./dump
