ci: implement a more robust mechanism to claim deposits

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -418,9 +418,9 @@ jobs:
 
       - name: Install polycli
         run: |
-          tmp_dir=$(mktemp -d) 
-          curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${{ env.POLYCLI_VERSION }}/polycli_${{ env.POLYCLI_VERSION }}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir" 
-          mv "$tmp_dir"/* /usr/local/bin/polycli 
+          tmp_dir=$(mktemp -d)
+          curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${{ env.POLYCLI_VERSION }}/polycli_${{ env.POLYCLI_VERSION }}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir"
+          mv "$tmp_dir"/* /usr/local/bin/polycli
           rm -rf "$tmp_dir"
           sudo chmod +x /usr/local/bin/polycli
           /usr/local/bin/polycli version
@@ -435,7 +435,7 @@ jobs:
         # This step will only execute if the necessary secrets are available, preventing failures
         # on pull requests from forked repositories.
         if: ${{ env.agglayer_prover_sp1_key && env.agglayer_prover_sp1_key != '' }}
-        env :
+        env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
       - name: Deploy L1 chain and a first CDK L2 chain (cdk-erigon sequencer + cdk stack)
@@ -500,43 +500,47 @@ jobs:
         run: |
           echo "Sending a bridge transaction from L1 to the PP network Erigon RPC..."
           bridge_address=$(kurtosis service exec ${{ env.ENCLAVE_NAME }} contracts-001 'jq -r .polygonZkEVMBridgeAddress /opt/zkevm/combined.json' 2>&1 | grep -P '0x\h*')
-          originNetworkURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc)
+          origin_network_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc)
           polycli ulxly bridge asset \
               --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
               --value 1000000000000000000 \
-              --rpc-url http://$originNetworkURL \
+              --rpc-url http://$origin_network_url \
               --bridge-address $bridge_address \
               --destination-network 3 \
               --force-update-root=true \
               --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970
           if [[ $ret_code -eq 0 ]]; then
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit Transaction successfuly sent!"
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit transaction successfuly sent!"
           else
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit Transaction failed!"
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit transaction failed!"
               exit 1
           fi
 
-          echo "Waiting for deposit to be claimable..."
-          sleep 60
-
-          destNetworkURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)
-          bridgeURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-bridge-service-003 rpc)
-          polycli ulxly claim asset \
-              --bridge-address $bridge_address \
-              --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
-              --deposit-count 3 \
-              --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970 \
-              --deposit-network 0 \
-              --rpc-url $destNetworkURL \
-              --bridge-service-url $bridgeURL \
-              --gas-price $(cast gas-price --rpc-url $destNetworkURL)
-          if [[ $ret_code -eq 0 ]]; then
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim Transaction successfuly sent!"
-              exit 0
-          else
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim Transaction failed!"
-              exit 1
-          fi
+          dest_network_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)
+          bridge_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-bridge-service-003 rpc)
+          while true; do
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🔄 Attempting to claim the deposit..."
+            result=$(polycli ulxly claim asset \
+                --bridge-address $bridge_address \
+                --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
+                --deposit-count 3 \
+                --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970 \
+                --deposit-network 0 \
+                --rpc-url $dest_network_url \
+                --bridge-service-url $bridge_url \
+                --gas-price $(cast gas-price --rpc-url $dest_network_url))
+            ret_code=$?
+            if [[ "$ret_code" -eq 0 ]]; then
+                echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim transaction successfuly sent!"
+                echo "Output: $result"
+                exit 0
+            else
+                echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim transaction failed! Retring in 15 seconds..."
+                echo "Output: $result"
+                echo
+                sleep 15
+            fi
+          done
         env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
@@ -546,47 +550,52 @@ jobs:
         run: |
           echo "Sending a bridge transaction from third PP network to the first rollup Erigon RPC..."
           bridge_address=$(kurtosis service exec ${{ env.ENCLAVE_NAME }} contracts-001 'jq -r .polygonZkEVMBridgeAddress /opt/zkevm/combined.json' 2>&1 | grep -P '0x\h*')
-          originNetworkURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)
+          origin_network_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-003 rpc)
           polycli ulxly bridge asset \
               --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
               --value 1000000000000 \
-              --rpc-url $originNetworkURL \
+              --rpc-url $origin_network_url \
               --bridge-address $bridge_address \
               --destination-network 1 \
               --force-update-root=true \
               --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970 \
-              --gas-price $(cast gas-price --rpc-url $originNetworkURL)
+              --gas-price $(cast gas-price --rpc-url $origin_network_url)
+          ret_code=$?
           if [[ $ret_code -eq 0 ]]; then
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit Transaction successfuly sent!"
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit transaction successfuly sent!"
           else
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit Transaction failed!"
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit transaction failed!"
               exit 1
           fi
 
-          echo "Waiting for deposit to be claimable..."
-          sleep 210
-
-          destNetworkURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc)
-          bridgeURL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-bridge-service-003 rpc)
-          polycli ulxly claim asset \
-              --bridge-address $bridge_address \
-              --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
-              --deposit-count 0 \
-              --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970 \
-              --deposit-network 3 \
-              --rpc-url $destNetworkURL \
-              --bridge-service-url $bridgeURL \
-              --gas-price $(cast gas-price --rpc-url $destNetworkURL)
-          if [[ $ret_code -eq 0 ]]; then
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim Transaction successfuly sent!"
-              exit 0
-          else
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim Transaction failed!"
-              exit 1
-          fi
+          dest_network_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc)
+          bridge_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-bridge-service-003 rpc)
+          while true; do
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🔄 Attempting to claim the deposit..."
+            result=$(polycli ulxly claim asset \
+                --bridge-address $bridge_address \
+                --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
+                --deposit-count 0 \
+                --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970 \
+                --deposit-network 3 \
+                --rpc-url $dest_network_url \
+                --bridge-service-url $bridge_url \
+                --gas-price $(cast gas-price --rpc-url $dest_network_url))
+            ret_code=$?
+            if [[ $ret_code -eq 0 ]]; then
+                echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim transaction successfuly sent!"
+                echo "Output: $result"
+                exit 0
+            else
+                echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim transaction failed! Retrying in 15 seconds..."
+                echo "Output: $result"
+                echo
+                sleep 15
+            fi
+          done
         env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
-          
+
       - name: Dump enclave
         if: ${{ !cancelled() }}
         run: kurtosis enclave dump ${{ env.ENCLAVE_NAME }} ./dump
@@ -668,9 +677,9 @@ jobs:
 
       - name: Install polycli
         run: |
-          tmp_dir=$(mktemp -d) 
-          curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${{ env.POLYCLI_VERSION }}/polycli_${{ env.POLYCLI_VERSION }}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir" 
-          mv "$tmp_dir"/* /usr/local/bin/polycli 
+          tmp_dir=$(mktemp -d)
+          curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${{ env.POLYCLI_VERSION }}/polycli_${{ env.POLYCLI_VERSION }}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir"
+          mv "$tmp_dir"/* /usr/local/bin/polycli
           rm -rf "$tmp_dir"
           sudo chmod +x /usr/local/bin/polycli
           /usr/local/bin/polycli version
@@ -685,7 +694,7 @@ jobs:
         # This step will only execute if the necessary secrets are available, preventing failures
         # on pull requests from forked repositories.
         if: ${{ env.agglayer_prover_sp1_key && env.agglayer_prover_sp1_key != '' }}
-        env :
+        env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
       # Only run this step if the SP1_PRIVATE_KEY secrets is available.
@@ -699,7 +708,7 @@ jobs:
       - name: Inspect enclave
         run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}
         if: ${{ env.agglayer_prover_sp1_key && env.agglayer_prover_sp1_key != '' }}
-        env :
+        env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
       - name: Send bridge transactions from L1 to OP Sovereign L2
@@ -710,7 +719,6 @@ jobs:
           l1_prefunded_mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
           private_key=$(cast wallet private-key --mnemonic "$l1_prefunded_mnemonic")
           eth_address=$(cast wallet address --private-key $private_key)
-
           polycli ulxly bridge asset \
               --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
               --destination-network 2 \
@@ -760,27 +768,31 @@ jobs:
               exit 1
           fi
 
-          echo "Waiting for deposit to be claimable..."
-          sleep 210
-
           l1_prefunded_mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
           private_key=$(cast wallet private-key --mnemonic "$l1_prefunded_mnemonic")
           eth_address=$(cast wallet address --private-key $private_key)
-          polycli ulxly claim asset \
-              --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
-              --bridge-service-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} sovereign-bridge-service-001 rpc) \
-              --deposit-count 0 \
-              --destination-address 0xc0FFee0000000000000000000000000000000001 \
-              --deposit-network 2 \
-              --private-key $private_key \
-              --rpc-url http://$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc)
-          if [[ $ret_code -eq 0 ]]; then
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim Transaction successfuly sent!"
-              exit 0
-          else
-              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim Transaction failed!"
-              exit 1
-          fi
+          while true; do
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🔄 Attempting to claim the deposit..."
+            result=$(polycli ulxly claim asset \
+                --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
+                --bridge-service-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} sovereign-bridge-service-001 rpc) \
+                --deposit-count 0 \
+                --destination-address 0xc0FFee0000000000000000000000000000000001 \
+                --deposit-network 2 \
+                --private-key $private_key \
+                --rpc-url http://$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc))
+            ret_code="$?"
+            if [[ $ret_code -eq 0 ]]; then
+                echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim transaction successfuly sent!"
+                echo "Output: $result"
+                exit 0
+            else
+                echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim transaction failed! Retrying in 15 seconds..."
+                echo "Output: $result"
+                echo
+                sleep 15
+            fi
+          done
         env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
@@ -827,12 +839,12 @@ jobs:
               exit 1
           fi
         env:
-            agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
-            
+          agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
+
       - name: Dump enclave
         if: ${{ !cancelled() && env.agglayer_prover_sp1_key && env.agglayer_prover_sp1_key != ''}}
         run: kurtosis enclave dump ${{ env.ENCLAVE_NAME }} ./dump
-        env :
+        env:
           agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
       - name: Upload enclave dump
