ci: test combinations check

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -51,3 +51,26 @@ jobs:
 
       - name: Run shellcheck
         run: find . -type f -name '*.sh' | sort | xargs -I {} shellcheck {}
+
+  gen:
+    name: Check test combinations
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Generate test combinations
+        working-directory: .github/tests
+        run: ./combine-ymls.sh
+
+      - name: Try to update test combinations
+        run: make gen
+      - name: Check if test combinations are up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "❌ Error: Test combinations are not up to date. Please run \`./combine-ymls.sh\`."
+            git status --porcelain
+            git diff
+            exit 1
+          else
+            echo "✅ Test combinations are up to date."
+          fi
