ci: move gas token, static ports and op rollup jobs to nightly

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -14,6 +14,155 @@ env:
   ENCLAVE_NAME: cdk
 
 jobs:
+  # Create the test matrix.
+  list-ymls:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Generate test combinations
+        working-directory: .github/tests
+        run: ./combine-ymls.sh
+
+      - id: set-matrix
+        run: |
+          files=$(ls -R \
+            ./.github/tests/gas-token/auto.yml \
+            ./.github/tests/static-ports/custom-static-ports.yml \
+            ./.github/tests/static-ports/default-static-ports.yml \
+            ./.github/tests/op-rollup/*.yml \
+            | grep -v 'additional-services.yml')
+          matrix=$(echo "$files" | jq -R -s -c 'split("\n")[:-1]')
+          echo "matrix=$matrix" >> $GITHUB_OUTPUT
+
+  # Deploy the package using the matrix of test files.
+  run-with-args:
+    needs: list-ymls
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    strategy:
+      fail-fast: false
+      matrix:
+        file_name: ${{ fromJson(needs.list-ymls.outputs.matrix) }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+        # This step will only execute if the necessary secrets are available, preventing failures
+        # on pull requests from forked repositories.
+        if: ${{ env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN }}
+        env:
+          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Install Kurtosis CDK tools
+        uses: ./.github/actions/setup-kurtosis-cdk
+
+      - name: Generate test combinations
+        working-directory: .github/tests
+        run: ./combine-ymls.sh
+
+      - name: Run Starlark
+        run: kurtosis run --enclave=${{ env.ENCLAVE_NAME }} --args-file=${{ matrix.file_name }} --show-enclave-inspect=false .
+
+      - name: Inspect enclave
+        run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}
+
+      - name: Verify static ports
+        run: |
+          if [[ ${{ matrix.file_name }} == "./.github/tests/static-ports/default-static-ports.yml" ]]; then
+            echo "Making sure public ports start by a 5 as defined by the static ports in the input_parser.star file."
+
+            ports=$(kurtosis enclave inspect ${{ env.ENCLAVE_NAME }} | sed -n '/^========================================== User Services ==========================================$/,$ p' | tail -n +3)
+            if ! wrong_ports=$(echo "$ports" | grep -vE '127.0.0.1:5|none'); then
+              echo "✅ Default static ports are set correctly."
+              exit 0
+            else
+              echo "wrong_ports: $wrong_ports"
+              echo "❌ Default static ports are not set correctly."
+              exit 1
+            fi
+          else
+            echo "Skipping."
+          fi
+
+      - name: Monitor CDK chain verified batches (Central RPC)
+        run: |
+          result=$(yq --raw-output '.args.consensus_contract_type' ${{ matrix.file_name }})
+          if [[ "$result" == "pessimistic" ]]; then
+            echo "Skipping block verification as consensus is pessimistic."
+          else
+            sequencer_type=$(yq --raw-output '.args.sequencer_type' ${{ matrix.file_name }})
+            rpc_name=""
+            if [[ "$sequencer_type" == "erigon" ]]; then
+              rpc_name="cdk-erigon-rpc-001"
+            elif [[ "$sequencer_type" == "zkevm" ]]; then
+              rpc_name="zkevm-node-rpc-001"
+            elif [[ "$sequencer_type" == "null" ]]; then
+              rpc_name="cdk-erigon-rpc-001"
+            else
+              echo "Unknown sequencer type: $sequencer_type"
+              exit 1
+            fi
+            echo "RPC name: $rpc_name"
+            ./.github/scripts/monitor-cdk-chain.sh \
+              --enclave ${{ env.ENCLAVE_NAME }} \
+              --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} $rpc_name rpc)
+          fi
+
+      - name: Monitor CDK chain verified batches (zkEVM Permissionless RPC)
+        run: |
+          result=$(yq --raw-output '.args.consensus_contract_type' ${{ matrix.file_name }})
+          if [[ "$result" == "pessimistic" ]]; then
+            echo "Skipping block verification as consensus is pessimistic."
+          else
+            result=$(yq --raw-output '.args.additional_services // [] | contains(["pless_zkevm_node"])' ${{ matrix.file_name }})
+            if [[ "$result" == "true" ]]; then
+              ./.github/scripts/monitor-cdk-chain.sh \
+                --enclave ${{ env.ENCLAVE_NAME }} \
+                --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-node-rpc-pless-001 rpc)
+            else
+              echo "Skipping batch verification as there is no zkevm permissionless RPC in the environment"
+            fi
+          fi
+
+      - name: Monitor OP rollup finalized blocks (OP CL RPC)
+        run: |
+          result=$(yq --raw-output '.deployment_stages.deploy_optimism_rollup' ${{ matrix.file_name }})
+          if [[ "$result" == "true" ]]; then
+            ./.github/scripts/monitor-op-rollup.sh \
+              --enclave ${{ env.ENCLAVE_NAME }} \
+              --cl-rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} op-cl-1-op-node-op-geth-op-kurtosis http)
+          else
+            echo "Skipping block verification as there is no OP rollup in the environment"
+          fi
+
+      - name: Dump enclave
+        if: ${{ !cancelled() }}
+        run: kurtosis enclave dump ${{ env.ENCLAVE_NAME }} ./dump
+
+      - name: Generate archive name
+        if: ${{ !cancelled() }}
+        run: |
+          file_name=$(basename "${{ matrix.file_name }}" ".yml")
+          archive_name="dump_run_with_args_${file_name}_${{ github.run_id }}"
+          echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
+          echo "Generated archive name: ${archive_name}"
+
+      - name: Upload enclave dump
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.ARCHIVE_NAME }}
+          path: ./dump
+
   # Deploy the package with a pre-deployed gas token.
   pre-deployed-gas-token:
     runs-on: ubuntu-latest
